import { AutoComplete } from 'material-ui';
import React from 'react';

// Search bar with auto completion componenet.

// Imagine you have a list of languages that you'd like to autosuggest.
const stations = [
	{"name": "Aircraft"},
	{"name": "Alamein"},
	{"name": "Albion"},
	{"name": "Alphington"},
	{"name": "Altona"},
	{"name": "Anstey"},
	{"name": "Armadale"},
	{"name": "Ascot Vale"},
	{"name": "Ashburton"},
	{"name": "Aspendale"},
	{"name": "Auburn"},
	{"name": "Balaclava"},
	{"name": "Batman"},
	{"name": "Baxter"},
	{"name": "Bayswater"},
	{"name": "Beaconsfield"},
	{"name": "Belgrave"},
	{"name": "Bell"},
	{"name": "Bentleigh"},
	{"name": "Berwick"},
	{"name": "Bittern"},
	{"name": "Blackburn"},
	{"name": "Bonbeach"},
	{"name": "Boronia"},
	{"name": "Box Hill"},
	{"name": "Brighton Beach"},
	{"name": "Broadmeadows"},
	{"name": "Brunswick"},
	{"name": "Burnley"},
	{"name": "Burwood"},
	{"name": "Camberwell"},
	{"name": "Canterbury"},
	{"name": "Cardinia Road"},
	{"name": "Carnegie"},
	{"name": "Carrum"},
	{"name": "Caulfield"},
	{"name": "Chatham"},
	{"name": "Chelsea"},
	{"name": "Cheltenham"},
	{"name": "Clayton"},
	{"name": "Clifton Hill"},
	{"name": "Coburg"},
	{"name": "Collingwood"},
	{"name": "Coolaroo"},
	{"name": "Craigieburn"},
	{"name": "Cranbourne"},
	{"name": "Crib Point"},
	{"name": "Croxton"},
	{"name": "Croydon"},
	{"name": "Dandenong"},
	{"name": "Darebin"},
	{"name": "Darling"},
	{"name": "Dennis"},
	{"name": "Diamond Creek"},
	{"name": "Diggers Rest"},
	{"name": "Eaglemont"},
	{"name": "East Camberwell"},
	{"name": "East Malvern"},
	{"name": "East Richmond"},
	{"name": "Edithvale"},
	{"name": "Elsternwick"},
	{"name": "Eltham"},
	{"name": "Epping"},
	{"name": "Essendon"},
	{"name": "Fairfield"},
	{"name": "Fawkner"},
	{"name": "Ferntree Gully"},
	{"name": "Flagstaff"},
	{"name": "Flemington Bridge"},
	{"name": "Flemington Racecourse"},
	{"name": "Flinders Street"},
	{"name": "Footscray"},
	{"name": "Frankston"},
	{"name": "Gardenvale"},
	{"name": "Gardiner"},
	{"name": "Ginifer"},
	{"name": "Glen Iris"},
	{"name": "Glen Waverley"},
	{"name": "Glenbervie"},
	{"name": "Glenferrie"},
	{"name": "Glenhuntly"},
	{"name": "Glenroy"},
	{"name": "Gowrie"},
	{"name": "Greensborough"},
	{"name": "Hallam"},
	{"name": "Hampton"},
	{"name": "Hartwell"},
	{"name": "Hastings"},
	{"name": "Hawksburn"},
	{"name": "Hawthorn"},
	{"name": "Heatherdale"},
	{"name": "Heathmont"},
	{"name": "Heidelberg"},
	{"name": "Heyington"},
	{"name": "Highett"},
	{"name": "Holmesglen"},
	{"name": "Hoppers Crossing"},
	{"name": "Hughesdale"},
	{"name": "Huntingdale"},
	{"name": "Hurstbridge"},
	{"name": "Ivanhoe"},
	{"name": "Jacana"},
	{"name": "Jewell"},
	{"name": "Jolimont"},
	{"name": "Jordanville"},
	{"name": "Kananook"},
	{"name": "Keilor Plains"},
	{"name": "Kensington"},
	{"name": "Keon Park"},
	{"name": "Kooyong"},
	{"name": "Laburnum"},
	{"name": "Lalor"},
	{"name": "Laverton"},
	{"name": "Leawarra"},
	{"name": "Lilydale"},
	{"name": "Lynbrook"},
	{"name": "Macaulay"},
	{"name": "Macleod"},
	{"name": "Malvern"},
	{"name": "McKinnon"},
	{"name": "Melbourne Central"},
	{"name": "Mentone"},
	{"name": "Merinda Park"},
	{"name": "Merlynston"},
	{"name": "Merri"},
	{"name": "Middle Brighton"},
	{"name": "Middle Footscray"},
	{"name": "Mitcham"},
	{"name": "Mont Albert"},
	{"name": "Montmorency"},
	{"name": "Moonee Ponds"},
	{"name": "Moorabbin"},
	{"name": "Mooroolbark"},
	{"name": "Mordialloc"},
	{"name": "Moreland"},
	{"name": "Morradoo"},
	{"name": "Mount Waverley"},
	{"name": "Murrumbeena"},
	{"name": "Narre Warren"},
	{"name": "Newmarket"},
	{"name": "Newport"},
	{"name": "Noble Park"},
	{"name": "North Brighton"},
	{"name": "North Melbourne"},
	{"name": "North Richmond"},
	{"name": "North Williamstown"},
	{"name": "Northcote"},
	{"name": "Nunawading"},
	{"name": "Oak Park"},
	{"name": "Oakleigh"},
	{"name": "Officer"},
	{"name": "Ormond"},
	{"name": "Pakenham"},
	{"name": "Parkdale"},
	{"name": "Parliament"},
	{"name": "Pascoe Vale"},
	{"name": "Patterson"},
	{"name": "Prahran"},
	{"name": "Preston"},
	{"name": "Regent"},
	{"name": "Reservoir"},
	{"name": "Richmond"},
	{"name": "Ringwood"},
	{"name": "Ringwood East"},
	{"name": "Ripponlea"},
	{"name": "Riversdale"},
	{"name": "Rosanna"},
	{"name": "Roxburgh Park"},
	{"name": "Royal Park"},
	{"name": "Rushall"},
	{"name": "Ruthven"},
	{"name": "Sandown Park"},
	{"name": "Sandringham"},
	{"name": "Seaford"},
	{"name": "Seaholme"},
	{"name": "Seddon"},
	{"name": "Showgrounds"},
	{"name": "Somerville"},
	{"name": "South Kensington"},
	{"name": "South Morang"},
	{"name": "South Yarra"},
	{"name": "Southern Cross"},
	{"name": "Spotswood"},
	{"name": "Springvale"},
	{"name": "St Albans"},
	{"name": "Stony Point"},
	{"name": "Strathmore"},
	{"name": "Sunbury"},
	{"name": "Sunshine"},
	{"name": "Surrey Hills"},
	{"name": "Syndal"},
	{"name": "Tecoma"},
	{"name": "Thomastown"},
	{"name": "Thornbury"},
	{"name": "Toorak"},
	{"name": "Tooronga"},
	{"name": "Tottenham"},
	{"name": "Tyabb"},
	{"name": "Upfield"},
	{"name": "Upper Ferntree Gully"},
	{"name": "Upwey"},
	{"name": "Victoria Park"},
	{"name": "Watergardens"},
	{"name": "Watsonia"},
	{"name": "Wattle Glen"},
	{"name": "Werribee"},
	{"name": "West Footscray"},
	{"name": "West Richmond"},
	{"name": "Westall"},
	{"name": "Westgarth"},
	{"name": "Westona"},
	{"name": "Williams Landing"},
	{"name": "Williamstown"},
	{"name": "Williamstown Beach"},
	{"name": "Willison"},
	{"name": "Windsor"},
	{"name": "Yarraman"},
	{"name": "Yarraville"}
]


// const getSuggestions = value => {
//   const inputValue = value.trim().toLowerCase();
// 	const inputLength = inputValue.length;

//   return inputLength === 0 ? [] : stations.filter(station =>
//     station.name.toLowerCase().slice(0, inputLength) === inputValue
// 	);
// };

class MaterialStationSearchDropDown extends React.Component {
  render() {
    return (
			<AutoComplete
				hintText="Type train station"
				dataSource={stations.map(station => station.name)}
				filter={AutoComplete.caseInsensitiveFilter}
				onNewRequest={(requestString) => {
					console.log(requestString);
				}}
			/>
    );
  }
}

export default MaterialStationSearchDropDown;
export { MaterialStationSearchDropDown };